const pages=[
{key:'inventory',id:'INV-01',name:'Inventário',detail:'Linhas e detalhe',title:'Mais itens, menos formulário',thesis:'Nome, estado e quantidade na linha. O detalhe reúne Carrying e Sell; o stepper mantém a quantidade acessível.',image:'01-outfitting-inventory-phone.png',question:'A linha é suficiente para o uso diário? Carrying precisa ficar sempre à vista?'},
{key:'loadout',id:'COM-01',name:'Loadout',detail:'Ataques e resultados',title:'O resultado ao lado do ataque',thesis:'OB ganha destaque junto da identidade. Contribuições ficam no Inspector, com uma ação separada para editar.',image:'02-combat-loadout-phone.png',question:'Nome, modo, origem e OB bastam na lista? Você sentiria falta das contribuições sempre visíveis?'},
{key:'defense',id:'COM-02',name:'Defesa',detail:'Resumo e editor',title:'Comparar conjuntos antes de editar',thesis:'A lista deixa os quatro resultados de DB disponíveis. Um editor próprio concentra equipamento e ajustes do conjunto.',image:'03-combat-defense-set-phone.png',question:'Prefere este editor ou os campos diretamente na lista? Os quatro DB devem aparecer sempre?'},
{key:'attack',id:'COM-03',name:'Ataque',detail:'Identidade e fórmula',title:'Começar pela fórmula',thesis:'Voltar, identidade e OB cabem num cabeçalho compacto. A fórmula fica acessível antes das opções secundárias.',image:'05-combat-attack-editor-head-phone.png',question:'O cabeçalho orienta bem? A fórmula aparece cedo o suficiente?'},
{key:'options',id:'COM-04',name:'Opções',detail:'Revelação progressiva',title:'Abrir apenas o que precisa mudar',thesis:'Seções recolhíveis resumem valores já configurados. Equipamento, modificadores e detalhes operacionais continuam acessíveis.',image:'04-combat-attack-editor-options-phone.png',question:'As opções ficam fáceis de encontrar? Alguma seção deveria começar sempre aberta?'}];
const $=s=>document.querySelector(s);let current=pages.find(p=>p.key===location.hash.slice(1))||pages[0],theme='light',width=390;let notes={};try{notes=JSON.parse(localStorage.getItem('rm-design-review-v1')||'{}')}catch{}
function render(){ $('#screens').innerHTML=pages.map(p=>`<button data-screen="${p.key}" aria-current="${p===current}"><span>${p.id}</span><span>${p.name}<small>${p.detail}</small></span></button>`).join('');$('#ref').textContent=current.id+' · proposta';$('#title').textContent=current.title;$('#thesis').textContent=current.thesis;$('#question').textContent=current.question;$('#reference-image').src='assets/'+current.image;$('#image-link').href='assets/'+current.image;$('#caption').textContent='Referência '+current.image+' · iPhone / PR #65';$('#decision').value=notes[current.key]?.decision||'pending';$('#comment').value=notes[current.key]?.comment||'';updateMock();history.replaceState(null,'','#'+current.key); }
function updateMock(){const url=`mock.html?v=2&screen=${current.key}&theme=${theme}`;const frame=$('#mock');if(frame.dataset.screen!==current.key){frame.src=url;frame.dataset.screen=current.key;}else if(frame.contentDocument){frame.contentDocument.documentElement.dataset.theme=theme;}$('#direct').href=url;$('.frame-wrap').style.width=width+'px';$('.frame-wrap').style.maxWidth=width===390?'100%':'none';}
function save(){notes[current.key]={decision:$('#decision').value,comment:$('#comment').value,version:2};try{localStorage.setItem('rm-design-review-v1',JSON.stringify(notes));$('#status').textContent='Rascunho salvo neste navegador; ainda não enviado.'}catch{$('#status').textContent='Não foi possível salvar neste navegador. Copie seu parecer antes de sair.'}}
$('#screens').onclick=e=>{const b=e.target.closest('[data-screen]');if(b){current=pages.find(p=>p.key===b.dataset.screen);render()}};document.querySelectorAll('[data-width]').forEach(b=>b.onclick=()=>{width=Number(b.dataset.width);document.querySelectorAll('[data-width]').forEach(x=>x.setAttribute('aria-pressed',x===b));updateMock()});document.querySelectorAll('button[data-theme]').forEach(b=>b.onclick=()=>{theme=b.dataset.theme;document.querySelectorAll('button[data-theme]').forEach(x=>x.setAttribute('aria-pressed',x===b));updateMock()});$('#compare').onclick=()=>{const show=$('#reference').hidden;$('#reference').hidden=!show;$('#compare').setAttribute('aria-expanded',show);$('#compare').textContent=show?'Ocultar referência':'Ver referência'};$('#comment').oninput=save;$('#decision').onchange=save;
function feedback(){const labels={pending:'Ainda não avaliado',approved:'Aprovo esta direção',adjust:'Aprovo com ajustes',rethink:'Prefiro outra direção'};return 'Rolemaster — revisão dos mocks v2\n\n'+pages.map(p=>`${p.id} — ${p.name}: ${labels[notes[p.key]?.decision||'pending']}${notes[p.key]?' (anotação da v'+(notes[p.key].version||1)+')':''}\n${notes[p.key]?.comment||'Sem comentário.'}`).join('\n\n')}
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(feedback());$('#status').textContent='Parecer copiado. Cole neste chat para registrar suas decisões.'}catch{$('#export').hidden=false;$('#export').value=feedback();$('#export').select();$('#status').textContent='Selecione e copie o parecer abaixo.'}};
if(document.modelContext?.registerTool){Promise.resolve(document.modelContext.registerTool({name:'read_design_review',title:'Ler parecer local',description:'Lê as avaliações e comentários locais desta revisão, sem enviá-los.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Use um objeto vazio.');return {version:1,feedback:feedback()}}})).catch(()=>{})}render();
